#!name=wechat110
#!desc=wechat110

[MITM]
hostname = weixin110.qq.com, security.wechat.com

[Script]
spotify-proto = type=http-response,script-path= https://raw.githubusercontent.com/zZPiglet/Task/master/asset/UnblockURLinWeChat.js,pattern=^https\:\/\/(weixin110\.qq|security.wechat)\.com\/cgi-bin\/mmspamsupport-bin\/newredirectconfirmcgi\?, max-size=0,requires-body=true,binary-mode=true,timeout=10,script-update-interval=0,enable=true
