#From http://script.hub/file/_start_/https://whatshub.top/module/caiyun.module/_end_/caiyun.sgmodule?type=surge-module&target=shadowrocket-module&del=true
#!name=彩云天气pro
#!desc=彩云天气pro

[URL Rewrite]
^https:\/\/ad\.caiyunapp\.com\/ - reject

[Script]
彩云天气pro = type=http-response, pattern=^http[s]?:\/\/biz\.(caiyunapp|cyapi)\.(com|cn)\/v2\/user.*$, script-path=https://raw.githubusercontent.com/WeiRen0/Scripts/main/cytq.js, requires-body=true

[MITM]
hostname = %APPEND% *.caiyunapp.com, *.cyapi.com, *.cyapi.cn, *.caiyunapp.cn
