#From http://script.hub/file/_start_/https://github.com/ddgksf2013/Rewrite/raw/master/Html/Q-Search.conf/_end_/Q-Search.sgmodule?type=qx-rewrite&target=shadowrocket-module&del=true
#!name=X-Search
#!desc=X-Search

[URL Rewrite]
# fy xxx (Google 译至中)
^https:\/\/duckduckgo.com\/\?q=fy\+([^&]+).+ https://translate.google.com/#view=home&op=translate&sl=auto&tl=zh-CN&text=$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+fy.+ https://translate.google.com/#view=home&op=translate&sl=auto&tl=zh-CN&text=$1 302
# db    xxx (豆瓣)
^https:\/\/duckduckgo.com\/\?q=db\+([^&]+).+ https://m.douban.com/search?query=$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+db.+ https://m.douban.com/search?query=$1 302
# zh    xxx (知乎)
^https:\/\/duckduckgo.com\/\?q=zh\+([^&]+).+ http://www.zhihu.com/search?q=$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+zh.+ http://www.zhihu.com/search?q=$1 302
# wb    xxx (微博)
^https:\/\/duckduckgo.com\/\?q=wb\+([^&]+).+ https://s.weibo.com/weibo/$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+wb.+ https://s.weibo.com/weibo/$1 302
# wx    xxx (微信)
^https:\/\/duckduckgo.com\/\?q=wx\+([^&]+).+ https://weixin.sogou.com/weixinwap?query=$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+wx.+ https://weixin.sogou.com/weixinwap?query=$1 302
# tt    xxx (Twitter)
^https:\/\/duckduckgo.com\/\?q=tt\+([^&]+).+ https://twitter.com/search?q=$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+tt.+ https://twitter.com/search?q=$1 302
# rd    xxx (Reddit)
^https:\/\/duckduckgo.com\/\?q=rd\+([^&]+).+ https://www.reddit.com/search?q=$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+rd.+ https://www.reddit.com/search?q=$1 302
# jd  xxx (京东)
^https:\/\/duckduckgo.com\/\?q=jd\+([^&]+).+ openapp.jdmobile://virtual?params={"des":"productList","keyWord":"$1","from":"search","category":"jump"} 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+jd.+ openapp.jdmobile://virtual?params={"des":"productList","keyWord":"$1","from":"search","category":"jump"} 302
# tb  xxx (淘宝)
^https:\/\/duckduckgo.com\/\?q=tb\+([^&]+).+ taobao://s.taobao.com?q=$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+tb.+ taobao://s.taobao.com?q=$1 302
# yt  xxx (YouTube)
^https:\/\/duckduckgo.com\/\?q=yt\+([^&]+).+ https://www.youtube.com/results?search_query=$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+yt.+ https://www.youtube.com/results?search_query=$1 302
# bd  xxx (百度搜索)
^https:\/\/duckduckgo.com\/\?q=bd\+([^&]+).+ https://www.baidu.com/s?wd=$1 302
^https:\/\/duckduckgo.com\/\?q=((.(?!bd))+)\+bd.+ https://www.baidu.com/s?wd=$1 302
# wj  xxx (维基搜索)
^https:\/\/duckduckgo.com\/\?q=wj\+([^&]+).+ https://zh.wikipedia.org/wiki/$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+wj.+ https://zh.wikipedia.org/wiki/$1 302
# gt  xxx (Google 图片)
^https:\/\/duckduckgo.com\/\?q=gt\+([^&]+).+ https://www.google.com/search?&tbm=isch&q=$3&gl=CN 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+gt.+ https://www.google.com/search?&tbm=isch&q=$3&gl=CN 302
# by  xxx (必应)
^https:\/\/duckduckgo.com\/\?q=by\+([^&]+).+ https://www.bing.com/search?q=$1 302
^https:\/\/duckduckgo.com\/\?q=([^+]+)\+by.+ https://www.bing.com/search?q=$1 302
#     xxx （无指令默认为 Google）
^https:\/\/duckduckgo.com\/\?q=(?!dl(c|e|j)(\+|%20))([^&]+).+ https://www.google.com/search?q=$3&gl=CN 302

[MITM]
hostname = %APPEND% duckduckgo.com
